# Generated by Django 6.0.4 on 2026-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Can the user currently access this course?'),
        ),
    ]
