# Generated by Django 6.0.4 on 2026-05-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasthistory',
            name='target_audience',
            field=models.CharField(max_length=255),
        ),
    ]
