# Generated by Django 6.0.4 on 2026-05-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_id',
            field=models.CharField(blank=True, help_text='Bunny Stream Video GUID for preview', max_length=255, null=True),
        ),
    ]
